-- Replace the host_user_id value with an existing Supabase auth.users id before running.
-- This seed creates the example meetups requested for MVP demos.

insert into public.meetups (
  host_user_id,
  title,
  description,
  category,
  location,
  starts_at,
  max_participants,
  estimated_cost_min,
  estimated_cost_max,
  language,
  host_name,
  whatsapp_link,
  additional_notes,
  status
) values
  (
    '00000000-0000-0000-0000-000000000000',
    'Korean BBQ in Sinchon',
    'Grab samgyeopsal near campus with a small mixed group. Great for first conversations and easy Korean food tips.',
    'Food',
    'Sinchon, near Yonsei main gate',
    now() + interval '1 day',
    6,
    18000,
    28000,
    'English and Korean',
    'Minji',
    'https://chat.whatsapp.com/example-kbbq',
    'We will pick a place with veggie side dishes.',
    'OPEN'
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'Cafe study near Yonsei',
    'Quiet study block with coffee breaks. Come for accountability, stay for campus cafe recommendations.',
    'Study',
    'Cafe around Yonsei-ro',
    now() + interval '2 days',
    4,
    5000,
    9000,
    'English',
    'Daniel',
    'https://chat.whatsapp.com/example-cafe',
    null,
    'OPEN'
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'Han River picnic',
    'Meet after class, buy snacks together, and relax by the river before sunset.',
    'Trip',
    'Yeouido Hangang Park',
    now() + interval '4 days',
    8,
    10000,
    18000,
    'English and Korean',
    'Jisoo',
    'https://chat.whatsapp.com/example-hanriver',
    'Bring a light jacket.',
    'OPEN'
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'Hongdae bar night',
    'Casual Friday night in Hongdae with students who want to explore safely in a small group.',
    'Drinks',
    'Hongdae entrance',
    now() + interval '5 days',
    5,
    15000,
    35000,
    'English',
    'Alex',
    'https://chat.whatsapp.com/example-hongdae',
    'Adults only. Please bring ID.',
    'OPEN'
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'Gwangjang Market food tour',
    'Try bindaetteok, kimbap, and street snacks while learning how to order at a busy traditional market.',
    'Culture',
    'Gwangjang Market',
    now() + interval '7 days',
    6,
    12000,
    25000,
    'English and Korean',
    'Seoyeon',
    'https://chat.whatsapp.com/example-market',
    null,
    'OPEN'
  );
