import type { PublicMeetup } from "@/lib/types";

const now = Date.now();

export const mockMeetups: PublicMeetup[] = [
  {
    id: "mock-kbbq",
    host_user_id: "mock",
    title: "Korean BBQ in Sinchon",
    description: "Grab samgyeopsal near campus with a small mixed group. Great for first conversations and easy Korean food tips.",
    category: "Food",
    location: "Sinchon, near Yonsei main gate",
    starts_at: new Date(now + 86400000).toISOString(),
    max_participants: 6,
    estimated_cost_min: 18000,
    estimated_cost_max: 28000,
    language: "English and Korean",
    host_name: "Minji",
    additional_notes: "We will pick a place with veggie side dishes.",
    status: "OPEN",
    approved_count: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "mock-cafe",
    host_user_id: "mock",
    title: "Cafe study near Yonsei",
    description: "Quiet study block with coffee breaks. Come for accountability, stay for campus cafe recommendations.",
    category: "Study",
    location: "Cafe around Yonsei-ro",
    starts_at: new Date(now + 2 * 86400000).toISOString(),
    max_participants: 4,
    estimated_cost_min: 5000,
    estimated_cost_max: 9000,
    language: "English",
    host_name: "Daniel",
    additional_notes: null,
    status: "OPEN",
    approved_count: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "mock-hanriver",
    host_user_id: "mock",
    title: "Han River picnic",
    description: "Meet after class, buy snacks together, and relax by the river before sunset.",
    category: "Trip",
    location: "Yeouido Hangang Park",
    starts_at: new Date(now + 4 * 86400000).toISOString(),
    max_participants: 8,
    estimated_cost_min: 10000,
    estimated_cost_max: 18000,
    language: "English and Korean",
    host_name: "Jisoo",
    additional_notes: "Bring a light jacket.",
    status: "OPEN",
    approved_count: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "mock-hongdae",
    host_user_id: "mock",
    title: "Hongdae bar night",
    description: "Casual Friday night in Hongdae with students who want to explore safely in a small group.",
    category: "Drinks",
    location: "Hongdae entrance",
    starts_at: new Date(now + 5 * 86400000).toISOString(),
    max_participants: 5,
    estimated_cost_min: 15000,
    estimated_cost_max: 35000,
    language: "English",
    host_name: "Alex",
    additional_notes: "Adults only. Please bring ID.",
    status: "OPEN",
    approved_count: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "mock-market",
    host_user_id: "mock",
    title: "Gwangjang Market food tour",
    description: "Try bindaetteok, kimbap, and street snacks while learning how to order at a busy traditional market.",
    category: "Culture",
    location: "Gwangjang Market",
    starts_at: new Date(now + 7 * 86400000).toISOString(),
    max_participants: 6,
    estimated_cost_min: 12000,
    estimated_cost_max: 25000,
    language: "English and Korean",
    host_name: "Seoyeon",
    additional_notes: null,
    status: "CLOSED",
    approved_count: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
